### ISSUE TITLE
XCM chains Integration

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/polkadex-ts#220]
## Phase 1

As we now created new interfaces for THEA, we are bringing all the already supported chains from Polkadex-UI repo to this package. We have already allowed some of the transfer - 

- [x] AssetHub to Polkadex - USDT, DED, PINK, USDC
- [x] Polkadot to Polkadex - DOT

Our next goal is to scale the XCM transfers for THEA to the next level by adding the remaining chains one at a time.

- [x] Astar to Polkadex - ASTR
- [x] Interlay to Polkadex - IBTC
- [x] Moonbeam to Polkadex - GLMR
- [x] Unique to Polkadex  - UNQ
- [x] Phala to Polkadex - PHA

Add the THEA withdrawal logic i.e. User should be able to withdraw thier asset from Polkadex network to other network.

This ends the migration of existing chains in `Polkadex-UI` repo to current package (`@polkadex/thea`).

## Phase 2

Allow foreign chain non-native assets transfer to Polkadex which are being supported by Polkadex network.

For example, Astar supports USDT, IBTC and more tokens which are already supported by Polkadex network, but we never integrated it frontend. Technically, Transfer for these assets should work. So, we will be testing and allowing these transfers.

1. AssetHub to Polkadex
    - DOT
2. Astar to Polkadex
    - USDT
    - USDC
    - IBTC
    - PHA
    - UNQ
    - PINK
3. Interlay to Polkadex
    - DOT
    - USDT
4. Moonbeam to Polkadex
    - PINK
    - IBTC
    - DED
    - PHA
    - USDC
    - ASTR
    - UNQ
    - USDT
5. Phala to Polkadex
    - DOT
    - GLMR
    - ASTR
    - PINK

## Phase 3

Apart from that, we will permit other cross-chain transfers in addition to transfers from another chain to Polkadex. 
For example - AssetHub to Polkadot or AssetHub to Astar. By this, There is a significant expansion of the THEA.

---- List will go here for other chains XCM transfer. Need to finalized it first
